# frontend/nginx.conf
server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # A mágica para SPAs: tenta servir o arquivo pedido, depois a pasta, e se nada for encontrado, serve o index.html
        try_files $uri $uri/ /index.html;
    }

    # Configuração para evitar erros de console sobre favicon
    location /favicon.ico {
        access_log off;
        log_not_found off;
    }
}
